version: '3.8'

services:
  # -------------------------
  # RABBITMQ - Message Broker
  # -------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "secret-cookie-for-cluster"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    user: "rabbitmq:rabbitmq"

  # -------------------------
  # REDIS - Cache / Blacklist
  # -------------------------
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server --appendonly yes --requirepass ""
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    user: "redis:redis"
  # -------------------------
  # USER SERVICE DATABASE
  # -------------------------
  user-db:
    image: postgres:15
    container_name: user-db-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  # USER SERVICE
  # -------------------------
  user-service:
    build: ./user-service
    container_name: user-service-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./user-service/.env
    environment:
      NODE_ENV: production
      PGSSLMODE: require
      PGCHANNELBINDING: require
      # Services
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-db:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ./user-service:/app
      - /app/node_modules

  # -------------------------
  # PRODUCT SERVICE DATABASE
  # -------------------------
  product-db:
    image: postgres:15
    container_name: product-db-dev
    environment:
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
      POSTGRES_DB: productdb
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  # PRODUCT SERVICE
  # -------------------------
  product-service:
    build: ./product-service
    container_name: product-service-dev
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PGSSLMODE: require
      PGCHANNELBINDING: require
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    env_file:
      - ./product-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      product-db:
        condition: service_healthy
    networks:
      - ecommerce-network
    volumes:
      - ./product-service:/app
      - /app/node_modules

  # -------------------------
  # ORDER SERVICE DATABASE
  # -------------------------
  order-db:
    image: postgres:15
    container_name: order-db-dev
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: orderdb
    ports:
      - "5435:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d orderdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  # ORDER SERVICE
  # -------------------------
  order-service:
    build: ./order-service
    container_name: order-service-dev
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      PGSSLMODE: require
      PGCHANNELBINDING: require
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      USER_SERVICE_URL: http://user-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
    env_file:
      - ./order-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      order-db:
        condition: service_healthy
      user-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - ecommerce-network
    volumes:
      - ./order-service:/app
      - /app/node_modules

    # -------------------------
  # PAYMENT DB
  # -------------------------
  payment-db:
    image: postgres:15
    container_name: payment-db-dev
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
      POSTGRES_DB: paymentdb
    ports:
      - "5436:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # -------------------------
  # PAYMENT SERVICE
  # -------------------------
  payment-service:
    build: ./payment-service
    container_name: payment-service-dev
    ports:
      - "3004:3004"
    env_file:
      - ./payment-service/.env
    environment:
      NODE_ENV: development
      PGSSLMODE: disable
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      ORDER_SERVICE_URL: http://order-service:3003
      API_URL: http://localhost:3000
    depends_on:
      - payment-db
      - redis
      - rabbitmq
    networks:
      - ecommerce-network
    volumes:
      - ./payment-service:/app
      - /app/node_modules
    command: npm run start:dev

  # -------------------------
  # API GATEWAY
  # -------------------------
  api-gateway:
    build: ./gateway
    container_name: api-gateway-dev
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    environment:
      NODE_ENV: development
      USER_SERVICE_URL: http://user-service:3001
      PRODUCT_SERVICE_URL: http://product-service:3002
      ORDER_SERVICE_URL: http://order-service:3003
      PAYMENT_SERVICE_URL: http://payment-service:3004
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
    networks:
      - ecommerce-network
    volumes:
      - ./gateway:/app
      - /app/node_modules
    command: npm run start:dev

networks:
  ecommerce-network:
    driver: bridge

volumes:
  user_data:
  product_data:
  order_data:
  payment_data:
  rabbitmq_data:
  redis_data: